[cache]
bind = "127.0.0.1:1337"
root_path = "./cache"
max_downloads = 1

[proxy]
nodes = [
    "http://127.0.0.1:1337"
]

[entries.nukular]
base_url = "https://cdn.stuhtmedia.de/radio_nukular/"
patterns = ["*.m4a"]
