[package]
name = "bcdn"
version = "0.1.0"
authors = ["Benedikt Reinartz <filmor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
warp = "0.2"
clap = "2"
reqwest = { version = "0.10", features = ["stream"] }
url = "2.1"
serde_derive = "1"
serde = "1"
blake3 = "0.3"
hex = { version = "0.4", features = ["serde"] }
serde_json = "1"
thiserror = "1"
futures-util = "0.3"