[package]
name = "bcdn"
version = "0.1.0"
authors = ["Benedikt Reinartz <filmor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.2"
actix-rt = "1.1"
actix-web = "2.0"
blake3 = "0.3"
clap = "2"
futures-util = "0.3"
hex = { version = "0.4", features = ["serde"] }
log = "0.4"
pretty_env_logger = "0.4"
reqwest = { version = "0.10", features = ["stream"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
thiserror = "1"
tokio = { version = "0.2", features = ["rt-threaded"] }
toml = "0.5"
url = "2.1"